stages:
  - build
  - test
  - push
  - deploy

variables:
  DOCKER_USER_ID: "gglagvn"

build-job:
  stage: build
  tags:
    - local-deploy
  script:
    - echo "Đang biên dịch mã nguồn..."
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - "*/target/*.jar"

test-job:
  stage: test
  tags:
    - local-deploy
  script:
    - echo "Đang chạy Unit Tests tối giản cho báo cáo..."
    - mvn test 

push-job:
  stage: push
  tags:
    - local-deploy
  script:
    # Không cần docker login lại vì bạn đã login thủ công thành công trên MSI
    - echo "Sử dụng phiên đăng nhập Docker có sẵn..."

    # API Gateway
    - docker build -t $DOCKER_USER_ID/api-gateway:latest ./api-gateway
    - docker push $DOCKER_USER_ID/api-gateway:latest

    # Auth Service
    - docker build -t $DOCKER_USER_ID/auth-service:latest ./auth-service
    - docker push $DOCKER_USER_ID/auth-service:latest

    # Post Service
    - docker build -t $DOCKER_USER_ID/post-service:latest ./post-service
    - docker push $DOCKER_USER_ID/post-service:latest

    # Comment Service
    - docker build -t $DOCKER_USER_ID/comment-service:latest ./comment-service
    - docker push $DOCKER_USER_ID/comment-service:latest

deploy-job:
  stage: deploy
  tags:
    - local-deploy
  script:
    - echo "Đang cập nhật Kubernetes..."
    - kubectl rollout restart deployment api-gateway
    - kubectl rollout restart deployment auth-service
    - kubectl rollout restart deployment post-service
    - kubectl rollout restart deployment comment-service
    - kubectl get pods