quarkus.http.port=8081
quarkus.application.name=auth-service

quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=${AUTH_DATASOURCE_URL:jdbc:mysql://localhost:3306/auth_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true}
quarkus.datasource.username=${AUTH_DATASOURCE_USERNAME:root}
quarkus.datasource.password=${AUTH_DATASOURCE_PASSWORD:123456}

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

quarkus.swagger-ui.always-include=true

app.jwt-secret=${JWT_SECRET:DayLaKhoaBiMatCuaNhom8RatDaiVaKhoDoanDeBaoMatToken1234567890}
app.jwt-expiration-milliseconds=604800000
