apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-config
data:
  # Hostname của MySQL trong K8s là tên của Service MySQL
  MYSQL_HOST: "mysql-service"
  AUTH_SERVICE_URL: "http://auth-service:8081"
  POST_SERVICE_URL: "http://post-service:8082"
  COMMENT_SERVICE_URL: "http://comment-service:8083"
  JWT_EXPIRATION: "604800000"