apiVersion: v1
kind: Secret
metadata:
  name: blog-secrets
type: Opaque
data:
  DB_PASSWORD: MTIzNDU2
  # Chuỗi mới đã khớp 100% với PowerShell của bạn
  JWT_SECRET: RGF5TGFLaG9hQmlNYXRDdWFOaG9tOFJhdERhaVZhS2hvRG9hbkRlQmFvTWF0VG9rZW4xMjM0NTY3ODkw