quarkus.http.port=8083
quarkus.application.name=comment-service

quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=${COMMENT_DATASOURCE_URL:jdbc:mysql://localhost:3306/comment_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true}
quarkus.datasource.username=${COMMENT_DATASOURCE_USERNAME:root}
quarkus.datasource.password=${COMMENT_DATASOURCE_PASSWORD:123456}

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# CORS - cho phep Frontend goi truc tiep
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:3002,http://localhost:3000,http://127.0.0.1:3002,http://127.0.0.1:3000
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Accept,Authorization,Content-Type


quarkus.swagger-ui.always-include=true

rabbitmq.queue.name=notification_queue
rabbitmq.exchange.name=notification_exchange
rabbitmq.routing.key=notification_routing_key

rabbitmq-host=${RABBITMQ_HOST:localhost}
rabbitmq-port=${RABBITMQ_PORT:5672}
rabbitmq-username=${RABBITMQ_USERNAME:guest}
rabbitmq-password=${RABBITMQ_PASSWORD:guest}

mp.messaging.outgoing.comment-events.connector=smallrye-rabbitmq
mp.messaging.outgoing.comment-events.exchange.name=${rabbitmq.exchange.name}
mp.messaging.outgoing.comment-events.exchange.type=topic

mp.messaging.incoming.notifications.connector=smallrye-rabbitmq
mp.messaging.incoming.notifications.queue.name=${rabbitmq.queue.name}
mp.messaging.incoming.notifications.exchange.name=${rabbitmq.exchange.name}
mp.messaging.incoming.notifications.exchange.type=topic
mp.messaging.incoming.notifications.routing-keys=${rabbitmq.routing.key}
