apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: gglagvn/api-gateway:v1
          ports:
            - containerPort: 8080
          env:
            - name: AUTH_SERVICE_URL
              valueFrom: {configMapKeyRef: {name: blog-config, key: AUTH_SERVICE_URL}}
            - name: POST_SERVICE_URL
              valueFrom: {configMapKeyRef: {name: blog-config, key: POST_SERVICE_URL}}
            - name: COMMENT_SERVICE_URL
              valueFrom: {configMapKeyRef: {name: blog-config, key: COMMENT_SERVICE_URL}}
            - name: APP_JWT_SECRET
              valueFrom: {secretKeyRef: {name: blog-secrets, key: JWT_SECRET}}
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080